apiVersion: v1
kind: Service
metadata:
  name: pretest-api-service
  namespace: pretest #需要再確認
spec:
  selector:
    app: pretest-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

