apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: {{ .Values.database.namespace }} 
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP