
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pretest-web-deploy
  namespace: {{ include "system.namespace" . }}
spec:
  selector: 
    matchLabels:
      app: pretest-web
  replicas: 1
  template:  
    metadata:
      labels:
        app: pretest-web
    spec:
      containers:
      - name: pretest-web
        image: asia-east1-docker.pkg.dev/refined-bolt-431903-u1/pretest/pretest-web:0.0.3
      imagePullSecrets:
      - name: regcred # GCP 上的 pull image secret name
