apiVersion: v1
kind: Service
metadata:
  name: pretest-web-service
  namespace: pretest #需要再確認
spec:
  selector:
    app: pretest-web
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  type: LoadBalancer

